version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: ["gunicorn", "src.wsgi:app", "--bind", "0.0.0.0:5000", "--reload"]
    container_name: backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./src:/my-company/src
      - ./tests:/my-company/tests
      - ./migrations:/my-company/migrations

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  db_test:
    image: postgres:13
    container_name: db_test
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRESS_DB=test

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres_data:
  pgadmin:

