"""

Revision ID: 8c878d14a1ee
Revises: cce10a53f502
Create Date: 2022-04-15 12:00:14.022796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c878d14a1ee'
down_revision = 'cce10a53f502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['owner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
