"""

Revision ID: e2afea140a4c
Revises: d95c3516af9a
Create Date: 2022-04-11 09:33:49.929242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2afea140a4c'
down_revision = 'd95c3516af9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('employer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['employer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'employer_id')
    # ### end Alembic commands ###
